### ISSUE TITLE
Exception when activating Tooltip in Chart

### ISSUE THREAD

**Issue by supermihi** [DevExpress/devextreme-reactive#1845]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [x] React Chart
- [ ] React Scheduler

### Current Behaviour
When I add the `<EventTracker/>` and `<ToolTip />` plugin to the chart, an exception occurs when I first hover the series:
```
Exception has occurred: TypeError
TypeError: Cannot read property 'size' of undefined
    at Function../node_modules/@devexpress/dx-chart-core/dist/dx-chart-core.es.js.getScatterPointTransformer.getTargetElement (c:\Users\XXX\node_modules\@devexpress\dx-chart-core\dist\dx-chart-core.es.js:539:14)
    at getParameters (c:\Users\XXX\node_modules\@devexpress\dx-chart-core\dist\dx-chart-core.es.js:920:1)
    at c:\Users\XXX\node_modules\@devexpress\dx-react-chart\dist\dx-react-chart.es.js:2434:43
    at TemplateConnectorBase../node_modules/@devexpress/dx-react-core/dist/dx-react-core.es.js.TemplateConnectorBase.render (c:\Users\XXX\node_modules\@devexpress\dx-react-core\dist\dx-react-core.es.js:508:1)
    at TemplateConnectorBase.hotComponentRender (c:\Users\XXX\node_modules\react-hot-loader\dist\react-hot-loader.development.js:730:1)
    at TemplateConnectorBase.proxiedRender (c:\Users\XXX\node_modules\react-hot-loader\dist\react-hot-loader.development.js:750:1)
    at finishClassComponent (c:\Users\XXX\node_modules\react-dom\cjs\react-dom.development.js:14391:1)
    at updateClassComponent (c:\Users\XXX\node_modules\react-dom\cjs\react-dom.development.js:14346:1)
    at beginWork (c:\Users\XXX\node_modules\react-dom\cjs\react-dom.development.js:15213:1)
    at performUnitOfWork (c:\Users\XXX\node_modules\react-dom\cjs\react-dom.development.js:18780:1)
```
The relevant code I am using:
```JSX
<Chart data={data}>
      <ArgumentAxis tickFormat={_ => tickFormat} />
      <ValueAxis tickFormat={_ => dimension.format} />
      <Palette scheme={myPalette} />
      {scenarios.map(s => (
        <LineSeries key={s.id} name={s.name} valueField={s.id} argumentField={...} />
      ))}
      <Animation />
      <Legend position="bottom" rootComponent={...} />
      <Title text="text" />
      <Stack />
      <EventTracker />
      <Tooltip />
    </Chart>
```

### Expected Behaviour
Tooltips should show without exception.

### Steps to Reproduce (for Bugs)
Try adding tooltip to a chart.

### Environment

- devextreme-reactive: 1.10.1
- react: 16.8.0
- browser: chrome
- bootstrap: 4.2.1
- react-bootstrap: none
- material-ui: none

**Comment by DmitryBogomolov** [comment]
Hello.

Thank you for pointing out to this issue.
Until we provide the fix, you can use the [following workaround](https://codesandbox.io/s/6222plkwjk).
